### ISSUE TITLE
vs2013编译失败 lbaselib.obj : error LNK2001: unresolved external symbol _nogc

### ISSUE THREAD

**Issue by zfl9** [Yu2erer/Lua-GC#2]
lbaselib.obj : error LNK2001: unresolved external symbol _nogc

**Comment by zfl9** [comment]
稍等，我检查下是不是我这边的cmake配置有问题。。

**Comment by zfl9** [comment]
```
lua\ygc.c(73): warning C4146: unary minus operator applied to unsigned type, result still unsigned
lua\ygc.c(83): warning C4146: unary minus operator applied to unsigned type, result still unsigned
lua\ygc.c(141): warning C4146: unary minus operator applied to unsigned type, result still unsigned
lua\ygc.c(163): warning C4146: unary minus operator applied to unsigned type, result still unsigned
lua\ygc.c(181): warning C4146: unary minus operator applied to unsigned type, result still unsigned
```
有几个警告，不知是否会有啥影响。

**Comment by zfl9** [comment]
我把lu_mem强制使用define替换为了ssize_t/long类型了。。

**Comment by Yu2erer** [comment]
> 我把lu_mem强制使用define替换为了ssize_t/long类型了。。

lu_mem 在Lua官方实现里面，它就是一个无符号的值，不需要转。最终结果一定是 大于 0 的。

**Comment by zfl9** [comment]
是的，但是vs2013编译有警告，因为这句代码：
```cpp
g->Y_GCmemnogc += (b ? mem : -mem);
```
看警告的意思是，-mem表达式的结果会变为unsigned的，应该是会有问题的吧

**Comment by Yu2erer** [comment]
> 是的，但是vs2013编译有警告，因为这句代码：
> 
> ```c++
> g->Y_GCmemnogc += (b ? mem : -mem);
> ```
> 
> 看警告的意思是，-mem表达式的结果会变为unsigned的，应该是会有问题的吧

运算结果 `Y_GCmemnogc` 不会是负数。 你如果觉得讨厌，可以把这个三目改成 if 语句 写多几行就不会报⚠️了。

**Comment by zfl9** [comment]
了解。
