### ISSUE TITLE
项目接入luajit后，同样的测试场景，速度更慢了

### ISSUE THREAD

**Issue by yaoyao1991** [Yu2erer/Lua-GC#4]

**Comment by yaoyao1991** [comment]
nogc和bggc暂时都没用，只做了luajit接入，发现程序速度更慢，cpu占用也更高了

**Comment by Yu2erer** [comment]
发生更慢的情况，可能是以下原因。
1.热点函数触发编译几率太低，可以适当调整热点函数编译的函数体大小。调整函数编译所需要的执行次数。
2.测试方式不准确，第一次压力测试的时大量函数很可能都触发了编译，这种时候自然是比原版慢的。加多几次压力测试，尽可能将热点函数覆盖编译完，再进行压测可以得到一个比较不错的数值，不然前几轮压测都在编译热点函数，自然会更慢。
